### ISSUE TITLE
Kodi only + Transmission

### ISSUE THREAD

**Issue by ijaureguialzo** [mrfixit2001/recalbox_rock64#1]
Hello, I've just found this project and is the only one I've managed to use for 4K HDR content on my Rock64.

I've already managed to make it boot to Kodi but was wondering how could I add Transmission to it. There are no sources in this repo and don't have any clue about where to start.

Is it even possible? Wouldn't mind trying to build it myself if it's there some procedure/docs.

Thanks!

**Comment by mrfixit2001** [comment]
Hello there! While this really doesn't qualify as an "issue", I'd be happy to try and assist. 
The Transmission addon is listed as supporting Leia (Kodi 18) so you should be able to find it in the official / standard kodi repository. This link might help answer some questions regarding repositories: https://www.addictivetips.com/media-streaming/kodi/best-repos-kodi-18-leia/

**Comment by ijaureguialzo** [comment]
OK, thanks for the tip. I will give it a try and post back results, if any.
