### ISSUE TITLE
CIFS issue?

### ISSUE THREAD

**Issue by swanee3d** [mrfixit2001/recalbox_rock64#2]
Hi, I can't seem to mount a external network share on any of the builds after the alpha release and when I run
`cat /proc/filesystems | awk '{print $NF}' | sed '/^$/d'
`
CIFS is missing from the list. 
Tried a newer official build on my Pi and everything works fine so I was wondering if this is a build issue?

**Comment by mrfixit2001** [comment]
CIFS now included in latest release
